### ISSUE TITLE
Not able to merge into this repo

### ISSUE THREAD

**Issue by JordanTranchina** [srobo/promotional-material#2]
I have the files but can't merge them in.

![screen shot 2019-02-20 at 12 28 06 pm](https://user-images.githubusercontent.com/41443492/53111401-fce01600-350a-11e9-8944-d2b1a58d449f.png)

**Comment by RealOrangeOne** [comment]
Did you fork the repo before making your changes? You don't have write permission for this repository, so you need to push your changes to a fork of this repo, and then create a pull request back into this repo.

**Comment by JordanTranchina** [comment]
You're right! I just made a fork and did a pull request successfully. Thanks for your help @RealOrangeOne!

This issue has been settled by Pull Request #3
