### ISSUE TITLE
Repo needs to be force pushed to remove large binary psd file from Tshirt merge request

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/promotional-material#8]

**Comment by Tyler-Ward** [comment]
This has now been completed.

@RealOrangeOne @TomWheal I have tagged you as your commits were on the edit chain. I will add the psd in a tag as on your repo. the only action you might need to take is to move your banner branch onto the new master.

**Comment by TomWheal** [comment]
Unsure why my force push didn’t work but thanks for fixing it.
